  #SINGLE LINE STATEMENT
a='THIS IS MY FIRST PYTHON PROGRAM'
print(a)

# SINGLE LINE SPECIAL PYTHON PROGRAM
a="THIS IS MY FIRST PYTHON's PROGRAM"
print (a)

#MULTI LINE PROGRAM
a='''HELLO THERE MY NAME IS PIYUSH 
   THIS ONE IS MULTI LINE PROGRAM'''
print(a)


